#!/bin/bash
set -e

MODELS_DIR="/models"
CONFIG_FILE="/opt/ComfyUI/extra_model_paths.yaml"
EXTRA_REQUIREMENTS="/opt/ComfyUI/extra-requirements.txt"

# Standard ComfyUI model type directories
MODEL_TYPES=(
    "checkpoints"
    "clip"
    "clip_vision"
    "configs"
    "controlnet"
    "diffusion_models"
    "embeddings"
    "gligen"
    "hypernetworks"
    "loras"
    "style_models"
    "text_encoders"
    "unet"
    "upscale_models"
    "vae"
    "vae_approx"
)

generate_model_paths() {
    echo "# Auto-generated by entrypoint.sh at $(date)"
    echo "# Scanning $MODELS_DIR for standard ComfyUI model directories"
    echo ""

    # Check if models directory exists
    if [[ ! -d "$MODELS_DIR" ]]; then
        echo "# Models directory $MODELS_DIR does not exist"
        return
    fi

    # Check which standard model type directories exist
    local found_any=false
    for model_type in "${MODEL_TYPES[@]}"; do
        if [[ -d "$MODELS_DIR/$model_type" ]]; then
            found_any=true
            break
        fi
    done

    if [[ "$found_any" == false ]]; then
        echo "# No standard model directories found in $MODELS_DIR"
        return
    fi

    # Generate YAML config
    echo "external_models:"
    echo "    base_path: $MODELS_DIR/"

    for model_type in "${MODEL_TYPES[@]}"; do
        if [[ -d "$MODELS_DIR/$model_type" ]]; then
            echo "    ${model_type}: ${model_type}/"
        fi
    done
}

echo "=== ComfyUI Entrypoint ==="

# Install extra requirements (allows dynamic package additions via ConfigMap)
if [[ -f "$EXTRA_REQUIREMENTS" ]]; then
    echo "Installing extra requirements from $EXTRA_REQUIREMENTS..."
    pip install --quiet -r "$EXTRA_REQUIREMENTS" || echo "Warning: Some packages may have failed to install"
    echo "Extra requirements installation complete."
else
    echo "No extra requirements file found at $EXTRA_REQUIREMENTS"
fi

echo ""
echo "Generating model paths configuration..."

# Generate the config file
generate_model_paths > "$CONFIG_FILE"

echo "Generated $CONFIG_FILE:"
cat "$CONFIG_FILE"
echo ""
echo "=== Starting ComfyUI ==="

# Execute the main command
exec "$@"
